name: Build

on:
  push
env:
  NODE_VERSION: '14.15.3'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: |
        npm install -g gatsby
        cd gatsby/lobid/
        npm ci
        gatsby build
